name: Issue report
description: Create a report to help us improve
title: "[ISSUE]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### Issue report form:

  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: "Check before posting"
      options:
        - label: I have checked [__existing issues__](https://github.com/israpps/FreeMcBoot-Installer/issues) for duplicates and found none
        - label: I am using a build downloaded from [this repository](https://israpps.github.io/FreeMcBoot-Installer/test/8_Downloads.html)

  - type: textarea
    id: explanation
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
      placeholder: My issue is...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Program setup
        > (please complete the following information):

  - type: input
    id: console
    attributes:
      label: Console model
      description: you can see it on the console sticker or inside OSDSYS (press triangle on main menu)
      placeholder: SCPH-????? | DTL-H????? | DESR-????
    validations:
      required: true

  - type: dropdown
    id: fmcborfhdb
    attributes:
      label: "Where do you have the issue?"
      multiple: false
      options:
        - FreeMcBoot
        - FreeMcBoot for PSX-DESR
        - FreeHdBoot
        - Installer
    validations:
      required: true

  - type: input
    id: oplver
    attributes:
      label: "Program version (if possible, also provide hash seen on installer used)"
      description: "Version of the software involved on issue"
      placeholder: "1.966"
    validations:
      required: true

  - type: dropdown
    id: changes
    attributes:
      label: "System modifications"
      description: "Aditional non-standard changes that are applied to the console"
      multiple: true
      options:
        - Modchip
        - MechaPWN
        - LensChanger

  - type: textarea
    id: context-and-data
    attributes:
      label: Context and extra information
      description: Information about affected features and expected behavior
      placeholder: "running an app in x circumstances cause z issue."
    validations:
      required: false
