#ifndef __LANG_H__
#define __LANG_H__

// Language IDs - Renamed to avoid conflict with osd_config.h
// These are used by UI.c's GetCurrentLanguage/SetCurrentLanguage and LoadLanguageStrings
enum FMCB_LANGUAGE_ID { // Renamed from LANGUAGE_ID
	FMCB_LANG_JAPANESE = 0, // Renamed from LANGUAGE_JAPANESE
	FMCB_LANG_ENGLISH,      // Renamed from LANGUAGE_ENGLISH
	FMCB_LANG_FRENCH,       // Renamed from LANGUAGE_FRENCH
	FMCB_LANG_SPANISH,      // Renamed from LANGUAGE_SPANISH
	FMCB_LANG_GERMAN,       // Renamed from LANGUAGE_GERMAN
	FMCB_LANG_ITALIAN,      // Renamed from LANGUAGE_ITALIAN
	FMCB_LANG_DUTCH,        // Renamed from LANGUAGE_DUTCH
	FMCB_LANG_PORTUGUESE,   // Renamed from LANGUAGE_PORTUGUESE
	//New languages can be added here.
	//The font contains all characters required for these languages.
	//If new languages like Russian and Chinese are to be supported, then new fonts must be added.
	//The English language strings are used as the default.

	FMCB_LANG_COUNT         // Renamed from LANG_COUNT, represents the number of supported languages
};

// String IDs
// These are IDs for strings that will be retrieved with GetString().
// New messages must be added before SYS_UI_MSG_COUNT.
enum SYS_UI_MSG_ID{
	SYS_UI_MSG_INSTALL_NORMAL_DESC = 0, 
	SYS_UI_MSG_INSTALL_MULTI_DESC,
	SYS_UI_MSG_CLEANUP_DESC,
	SYS_UI_MSG_CLEANUP_MULTI_DESC,
	SYS_UI_MSG_FORMAT_DESC,
	SYS_UI_MSG_DUMP_MC_DESC,
	SYS_UI_MSG_RESTORE_MC_DESC,
	SYS_UI_MSG_INSTALL_FHDB_DESC,
	SYS_UI_MSG_CLEANUP_FHDB_DESC,
	SYS_UI_MSG_INSTALL_CROSS_PSX_DESC,
	SYS_UI_MSG_FORMAT_HDD_DESC,
	SYS_UI_MSG_EXIT_DESC, 

	SYS_UI_MSG_PROMPT_CONTINUE,
	SYS_UI_MSG_PROMPT_INSTALL_NORMAL,
	SYS_UI_MSG_PROMPT_INSTALL_MULTI,
	SYS_UI_MSG_PROMPT_CLEANUP,
	SYS_UI_MSG_PROMPT_CLEANUP_MULTI,
	SYS_UI_MSG_PROMPT_INSTALL_FHDB,
	SYS_UI_MSG_PROMPT_CLEANUP_FHDB,
	SYS_UI_MSG_PROMPT_INSTALL_CROSS_PSX,

	SYS_UI_MSG_INSTALLING_NORMAL,
	SYS_UI_MSG_INSTALLING_MULTI,
	SYS_UI_MSG_INSTALLING_FHDB,
	SYS_UI_MSG_INSTALLING_CROSS_PSX,
	SYS_UI_MSG_INSTALL_COMPLETED,
	SYS_UI_MSG_INSTALL_FAILED,

	SYS_UI_MSG_CLEANING_UP,
	SYS_UI_MSG_CLEANUP_FAILED,
	SYS_UI_MSG_CLEANUP_COMPLETED,

	SYS_UI_MSG_FORMATTING_MC,
	SYS_UI_MSG_FORMATTING_HDD,
	SYS_UI_MSG_FORMAT_COMPLETED,
	SYS_UI_MSG_FORMAT_FAILED,

	SYS_UI_MSG_DUMPING_MC,
	SYS_UI_MSG_DUMPING_COMPLETED,
	SYS_UI_MSG_DUMPING_FAILED,

	SYS_UI_MSG_RESTORING_MC,
	SYS_UI_MSG_RESTORING_COMPLETED,
	SYS_UI_MSG_RESTORING_FAILED,

	SYS_UI_MSG_HAS_MULTI_INST,
	SYS_UI_MSG_MULTI_INST_REQ,
	SYS_UI_MSG_NO_MC,
	SYS_UI_MSG_MC_INVALID_FMT,
	SYS_UI_MSG_NO_SPACE,
	SYS_UI_MSG_NO_SPACE_HDD,
	SYS_UI_MSG_NO_SPACE_HDD_APPS,
	SYS_UI_MSG_LOADING_LANG,
	SYS_UI_MSG_UNSUPP_CONSOLE, 
	SYS_UI_MSG_NO_HDD,         
	SYS_UI_MSG_HDD_CORRUPTED,  
	SYS_UI_MSG_PLEASE_WAIT,

	SYS_UI_MSG_QUIT_DUMPING,   
	SYS_UI_MSG_QUIT_RESTORING, 

	// Description strings for main menu items (referenced in menu.c MainMenuUpdateCallback)
	SYS_UI_MSG_DSC_INST_FMCB,
	SYS_UI_MSG_DSC_MI_FMCB,
	SYS_UI_MSG_DSC_UINST_FMCB,
	SYS_UI_MSG_DSC_DOWNGRADE_MI,
	SYS_UI_MSG_DSC_FORMAT_MC,
	SYS_UI_MSG_DSC_DUMP_MC,
	SYS_UI_MSG_DSC_REST_MC,
	SYS_UI_MSG_DSC_INST_CROSS_PSX,
	SYS_UI_MSG_DSC_INST_FHDB,
	SYS_UI_MSG_DSC_UINST_FHDB,
	SYS_UI_MSG_DSC_FORMAT_HDD,
	SYS_UI_MSG_DSC_QUIT,

	// OpenTuna Installer Messages 
	SYS_UI_MSG_OT_AUTO_START,
	SYS_UI_MSG_OT_MANUAL_SELECT_PAYLOAD,
	SYS_UI_MSG_OT_CLEANUP_START,
	SYS_UI_MSG_OT_ERR_UNSUPPORTED_MODEL,
	SYS_UI_MSG_OT_WARN_CLEANUP_ISSUES,
	SYS_UI_MSG_OT_ERR_INSTALL_FAILED,
	SYS_UI_MSG_OT_WARN_TIMESTAMP_FAILED,
	SYS_UI_MSG_OT_SUCCESS_AUTO,
	SYS_UI_MSG_OT_SUCCESS_MANUAL,
	SYS_UI_MSG_OT_MANUAL_CANCELLED,
	SYS_UI_MSG_OT_CLEANUP_SUCCESS,
	SYS_UI_MSG_OT_AUTO_CONFIRM,
	SYS_UI_MSG_OT_MANUAL_CONFIRM,
	SYS_UI_MSG_OT_CLEANUP_CONFIRM,
	
	SYS_UI_MSG_DSC_OPENTUNA_INSTALLER, // Description for OpenTuna Installer main menu item

	// Original FMCB Installer messages that were after the block of descriptions
	SYS_UI_MSG_MULTI_WARN,
	SYS_UI_MSG_QUIT,
	SYS_UI_MSG_FORMAT_HDD_MANUAL,
	SYS_UI_MSG_FORMAT_HDD_FAILED,
	SYS_UI_MSG_RARE_ROMVER,
	SYS_UI_MSG_ROM_UNSUPPORTED,
	SYS_UI_MSG_CNF_FOUND,
	SYS_UI_MSG_CNF_HDD_FOUND,
	SYS_UI_MSG_MULTIPLE_CARDS,
	SYS_UI_MSG_INST_CFM_SLOT1,
	SYS_UI_MSG_INST_CFM_SLOT2,
	SYS_UI_MSG_INST_CFM_HDD,
	SYS_UI_MSG_INST_PROMPT_INST_TYPE,
	SYS_UI_MSG_CLNUP_CFM_SLOT1,
	SYS_UI_MSG_CLNUP_CFM_SLOT2,
	SYS_UI_MSG_CLNUP_CFM_HDD,
	SYS_UI_MSG_FORMAT_CFM_SLOT1,
	SYS_UI_MSG_FORMAT_CFM_SLOT2,
	SYS_UI_MSG_DUMP_CFM_SLOT1,
	SYS_UI_MSG_DUMP_CFM_SLOT2,
	SYS_UI_MSG_RESTORE_CFM_SLOT1,
	SYS_UI_MSG_RESTORE_CFM_SLOT2,
	SYS_UI_MSG_UNINSTALLING_FMCB,
	SYS_UI_MSG_UNINSTALLING_FHDB,
	SYS_UI_MSG_NO_ENT_ERROR,
	SYS_UI_MSG_READ_INST_ERROR,
	SYS_UI_MSG_WRITE_INST_ERROR,
	SYS_UI_MSG_READ_MC_ERROR,
	SYS_UI_MSG_WRITE_MC_ERROR,
	SYS_UI_MSG_WRITE_HDD_ERROR,
	SYS_UI_MSG_NO_MEM_ERROR,
	SYS_UI_MSG_CACHE_INIT_ERROR,
	SYS_UI_MSG_CROSSLINK_FAIL,
	SYS_UI_MSG_MG_BIND_FAIL,
	SYS_UI_MSG_UNSUPPORTED_UINST_FILE_ERROR,
	SYS_UI_MSG_HDD_SMART_FAILED,
	SYS_UI_MSG_INSUF_FREE_SPC,
	SYS_UI_MSG_INSUF_FREE_SPC_HDD_APPS,
	SYS_UI_MSG_INSUF_FREE_SPC_HDD,

	SYS_UI_MSG_COUNT // This must be the last one!
};

// Label IDs
// These are IDs for labels that will be retrieved with GetUILabel().
// New labels must be added before SYS_UI_LBL_COUNT.
enum SYS_UI_LBL_ID{
	SYS_UI_LBL_OK = 0,
	SYS_UI_LBL_CANCEL,
	SYS_UI_LBL_YES,
	SYS_UI_LBL_NO,
	SYS_UI_LBL_WARNING, 
	SYS_UI_LBL_ERROR,   
	SYS_UI_LBL_INFO,    
	SYS_UI_LBL_CONFIRM, 
	SYS_UI_LBL_WAIT,    
	SYS_UI_LBL_NOTICE,  
	
	// Standard FMCB Labels
	SYS_UI_LBL_SLOT1,
	SYS_UI_LBL_SLOT2,
	SYS_UI_LBL_MEMORY_CARD, 
	SYS_UI_LBL_HDD,         
	SYS_UI_LBL_INSTALLING,
	SYS_UI_LBL_DUMPING_MC_PROG,  
	SYS_UI_LBL_RESTORING_MC_PROG,
	SYS_UI_LBL_INSTALL_THIS_PS2, 
	SYS_UI_LBL_INSTALL_SAME_REGION,
	SYS_UI_LBL_INSTALL_ALL_PS2,    
	SYS_UI_LBL_RATE,
	SYS_UI_LBL_ETA,                
	SYS_UI_LBL_INSTALL,            
	SYS_UI_LBL_MI,                 
	SYS_UI_LBL_UINSTALL,           
	SYS_UI_LBL_UMI,                
	SYS_UI_LBL_FORMAT_MC,          
	SYS_UI_LBL_DUMP_MC,            
	SYS_UI_LBL_REST_MC,            
	SYS_UI_LBL_INSTALL_CROSS_PSX,  
	SYS_UI_LBL_INSTALL_FHDB,       
	SYS_UI_LBL_UINSTALL_FHDB,      
	SYS_UI_LBL_EXIT,               
	SYS_UI_LBL_B,
	SYS_UI_LBL_KB,
	SYS_UI_LBL_MB,
	SYS_UI_LBL_GB,
	SYS_UI_LBL_TB, 
	SYS_UI_LBL_BPS,  
	SYS_UI_LBL_KBPS, 
	SYS_UI_LBL_MBPS, 
	SYS_UI_LBL_AVAILABLE_SPC,
	SYS_UI_LBL_REQUIRED_SPC,
	SYS_UI_LBL_MENU_MAIN,
	SYS_UI_LBL_MENU_EXTRAS,
	SYS_UI_LBL_MENU_MC,
	SYS_UI_LBL_FORMAT_HDD,         
	SYS_UI_LBL_ENABLED,            
	SYS_UI_LBL_DISABLED,           
	SYS_UI_LBL_INST_TYPE_NORMAL,   
	SYS_UI_LBL_INST_TYPE_CRS_MDL,  
	SYS_UI_LBL_INST_TYPE_CRS_REG,  

	// OpenTuna Installer Labels
	SYS_UI_LBL_OT_MENU_TITLE,
	SYS_UI_LBL_OT_ITEM_AUTO,
	SYS_UI_LBL_OT_ITEM_MANUAL,
	SYS_UI_LBL_OT_ITEM_CLEANUP,
	SYS_UI_LBL_OT_MANUAL_SELECT_TITLE,
	SYS_UI_LBL_OT_PAYLOAD_SLIMS,
	SYS_UI_LBL_OT_PAYLOAD_FATS,
	SYS_UI_LBL_OT_PAYLOAD_FAT170,

	SYS_UI_LBL_COUNT // This must be the last one!
};

// Function Prototypes
const char *GetString(unsigned int StrID); 
const char *GetUILabel(unsigned int LblID); 

int LoadLanguageStrings(enum FMCB_LANGUAGE_ID languageId); // MODIFIED parameter type
int LoadDefaultLanguageStrings(void); 
void UnloadLanguage(void); 

int GetCurrentLanguage(void); // Should return enum FMCB_LANGUAGE_ID
void SetCurrentLanguage(enum FMCB_LANGUAGE_ID languageId); // MODIFIED parameter type

#endif /* __LANG_H__ */
